export enum APPOINTMENTS_STEPS {
  APPOINTMENT_INITIAL,
  APPOINTMENT_CONFIRMATION,
  APPOINTMENT_SUCCESS,
}

export const APPOINTMENT_TYPES = {
  SPECIALTY: 'specialty',
  PROFESSIONAL: 'professional',
} as const;

export const PRIORITY_TYPES = {
  PROXIMITY: 'proximity',
  AVAILABILITY: 'availability',
} as const;

export const USER_TYPE = {
  PATIENT: 'paciente',
  PROFESSIONAL: 'profesional',
  ADMINISTRATIVE: 'administrativo',
} as const;

export const APPOINTMENT_STATUSES = {
  ABSENT: 'ABSENT',
  CANCELLED: 'CANCELLED',
  CHECKED_IN: 'CHECKED_IN',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  CONFIRMED: 'CONFIRMED',
  EXPIRED: 'EXPIRED',
  PENDING_CONFIRMATION: 'PENDING_CONFIRMATION',
} as const;